---
- hosts: www

  vars:
    - root_dir: ..
    - custom_mongo_version: "3.4"


  pre_tasks:
    - debug: msg="{{custom_mongo_version}}"

  roles:
     - {
         role: "sa-mongo-percona",
         mongo_version: "{{custom_mongo_version}}",
         mongo_bind_ip: "0.0.0.0"
       }


  tasks:
    - debug: msg="Tasks section"
